# Generated by Django 5.1.1 on 2024-09-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_alter_user_managers_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
