# Generated by Django 5.1.1 on 2024-09-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0004_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='order_product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
